### ISSUE TITLE
Fails to run with Ubuntu 22.04

### ISSUE THREAD

**Issue by JanneKiiskila** [PelionIoT/e2e-edge-test-suite#15]
The command `pytest --config_path=<file.json> --html=results.html` fails to run on Ubuntu 22.04.
- I am suspecting that the requirements.txt has not pinned versions down accurately enough and some dependency now has changed behavior.

```
pytest --config_path=config-rpi3.json --html=results.html
Traceback (most recent call last):
  File "/home/jannek/.local/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/jannek/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/home/jannek/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/home/jannek/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/jannek/.local/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jannek/.local/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jannek/.local/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/jannek/.local/lib/python3.10/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/jannek/.local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/jannek/.local/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jannek/.local/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/jannek/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/home/jannek/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/home/jannek/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/jannek/.local/lib/python3.10/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/jannek/.local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 161, in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
  File "/home/jannek/.local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 356, in _rewrite_test
    co = compile(tree, fn_, "exec", dont_inherit=True)
TypeError: required field "lineno" missing from alias
```

The following packages are in the pip list for the virtual environment being used.

```
(venv) jannek@jannek-P720:/ssd/e2e-edge-test-suite$ pip list
Package              Version
-------------------- ---------
aiohttp              3.8.1
aiosignal            1.2.0
async-timeout        4.0.2
attrs                22.1.0
cachetools           5.2.0
certifi              2022.6.15
charset-normalizer   2.1.1
frozenlist           1.3.1
google-auth          2.11.0
idna                 3.3
iniconfig            1.1.1
Jinja2               3.1.2
kubernetes           10.0.1
MarkupSafe           2.1.1
multidict            6.0.2
oauthlib             3.2.0
packaging            21.3
pip                  22.2.2
pluggy               0.13.1
py                   1.11.0
pyasn1               0.4.8
pyasn1-modules       0.2.8
pyparsing            3.0.9
pytest               6.2.2
pytest-html          1.22.0
pytest-metadata      2.0.2
pytest-rerunfailures 10.2
python-dateutil      2.8.2
PyYAML               6.0
requests             2.28.1
requests-oauthlib    1.3.1
rsa                  4.9
setuptools           63.4.1
six                  1.16.0
toml                 0.10.2
urllib3              1.26.12
websocket-client     1.3.3
wheel                0.37.1
ws4py                0.5.1
yarl                 1.8.1
```

**Comment by JanneKiiskila** [comment]
This is actually not in issue in this repo, it's an incompatibility on on the pytest side.
You can fix it by updating pytest to latest version.

Run `pip install -U pytest` and it will work after that.

Ref: https://stackoverflow.com/questions/69528842/an-error-while-trying-to-execute-tests-on-python-3-10-with-pytest

Confirmed that this fixes the issue.

**Comment by JanneKiiskila** [comment]
https://github.com/PelionIoT/e2e-edge-test-suite/pull/16 - resolves it.
